In [51]:
import numpy as np

In [52]:
basismat = [[0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35],
            [0.49, 0.42, 0.28, 0.10, -0.10, -0.28, -0.42, -0.49],
            [0.46, 0.19, -0.19, -0.46, -0.46, -0.19, 0.19, 0.46],
            [0.42, -0.10, -0.49, -0.28, 0.28, 0.49, 0.10, -0.42],
            [0.35, -0.35, -0.35, 0.35, 0.35, -0.35, -0.35, 0.35],
            [0.28, -0.49, 0.10, 0.42, -0.42, -0.10, 0.49, -0.28],
            [0.19, -0.46, 0.46, -0.19, -0.19, 0.46, -0.46, 0.19],
            [0.10, -0.28, 0.42, -0.49, 0.49, -0.42, 0.28, -0.10]]
basismat

[[0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35],
 [0.49, 0.42, 0.28, 0.1, -0.1, -0.28, -0.42, -0.49],
 [0.46, 0.19, -0.19, -0.46, -0.46, -0.19, 0.19, 0.46],
 [0.42, -0.1, -0.49, -0.28, 0.28, 0.49, 0.1, -0.42],
 [0.35, -0.35, -0.35, 0.35, 0.35, -0.35, -0.35, 0.35],
 [0.28, -0.49, 0.1, 0.42, -0.42, -0.1, 0.49, -0.28],
 [0.19, -0.46, 0.46, -0.19, -0.19, 0.46, -0.46, 0.19],
 [0.1, -0.28, 0.42, -0.49, 0.49, -0.42, 0.28, -0.1]]

In [53]:
fx = [0, 0, 0, 1, 1, 0, 0, 0]
fx

[0, 0, 0, 1, 1, 0, 0, 0]

In [54]:
res = np.matmul(basismat, fx)
res

array([ 0.7 ,  0.  , -0.92,  0.  ,  0.7 ,  0.  , -0.38,  0.  ])

In [55]:
res2 = np.matmul(res, basismat)
print(res2)
print(np.round(res2))

[-5.40000000e-03 -1.28785871e-18 -2.64677169e-17  9.85400000e-01
  9.85400000e-01 -2.64677169e-17 -1.28785871e-18 -5.40000000e-03]
[-0. -0. -0.  1.  1. -0. -0. -0.]


In [56]:
res[2:] = 0
res

array([0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. ])

In [57]:
res2 = np.matmul(res, basismat)
print(res2)
print(np.round(res2))

[0.245 0.245 0.245 0.245 0.245 0.245 0.245 0.245]
[0. 0. 0. 0. 0. 0. 0. 0.]
